name: portfolio-prod

services:
  web:
    image: ghcr.io/wiktorwijata/portfolio-web:${WEB_TAG:-latest}
    container_name: portfolio-web-prod
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - prod

networks:
  prod:
    external: true
